### ISSUE TITLE
Cannot find package on MELPA

### ISSUE THREAD

**Issue by eullerborges** [google/vc-defer#1]
Hi, I could not find this package listed on MELPA. I'm currently using Spacemacs on the develop branch, but I couldn't install this through `use-package` either. So, I guess there are two questions:
1. Are there plans to provide this on MELPA?
2. What are the instructions for manual installation?

Thanks!

**Comment by tomfitzhenry** [comment]
I'm going to try this.

**Comment by tomfitzhenry** [comment]
I've raised https://github.com/melpa/melpa/pull/7214 .

**Comment by tomfitzhenry** [comment]
vc-defer is now on MELPA: https://melpa.org/#/vc-defer
